### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by hermanc-fda** [usabilityhub/ts-auto-guard#77]
Maybe this is just me but no matter what I do, I can't install the latest version of this package. npm install obviously won't work because the latest version is not published, but doing npm install with references to git repo usually works like a charm. I must've spent a couple hours on this and am completely baffled. Any ideas?

**Comment by rhys-vdw** [comment]
@hermanc-fda it should work... You may need to navigate into the install directory and run `npm build` in there to build it? What are you adding to your `package.json`?

**Comment by hermanc-fda** [comment]
package.json I had to add the github repo, otherwise it downloads an older version. But it has some install errors so I had to manually clone to node_modules, go inside there, then npm build and run the cli 😅  Whatever works ;) I'll close since I hacked it to work for myself! Thanks

**Comment by hermanc-fda** [comment]
BTW it's great when it works, thanks.
